# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('trello', 'Trello')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('origin_id', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], db_index=True, default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin_id', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['workspace', 'origin_id'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workspaces.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='workspaces.DataSourceUser')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('origin_id', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], db_index=True, default='open', max_length=10)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='GitHubDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workspaces.DataSource')),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('workspaces.datasource',),
        ),
        migrations.CreateModel(
            name='TrelloDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workspaces.DataSource')),
                ('key', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=50, verbose_name='Trello organization ID')),
            ],
            bases=('workspaces.datasource',),
        ),
        migrations.CreateModel(
            name='TrelloWorkspace',
            fields=[
                ('workspace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workspaces.Workspace')),
                ('in_progress_list', models.CharField(max_length=100)),
            ],
            bases=('workspaces.workspace',),
        ),
        migrations.AddField(
            model_name='workspace',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='workspaces.DataSource'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='projects',
            field=models.ManyToManyField(db_index=True, related_name='workspaces', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, through='workspaces.TaskAssignment', to='workspaces.DataSourceUser'),
        ),
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspaces.Workspace'),
        ),
        migrations.AddField(
            model_name='datasourceuser',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source_users', to='workspaces.DataSource'),
        ),
        migrations.AddField(
            model_name='datasourceuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_source_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='users',
            field=models.ManyToManyField(through='workspaces.DataSourceUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together=set([('data_source', 'origin_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set([('user', 'task')]),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('workspace', 'origin_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='datasourceuser',
            unique_together=set([('data_source', 'user'), ('data_source', 'username'), ('data_source', 'origin_id')]),
        ),
    ]
