# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('position', models.FloatField(null=True)),
                ('origin_id', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], db_index=True, default='open', max_length=10)),
                ('task_state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='trelloworkspace',
            name='workspace_ptr',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'created_at', 'ordering': ['workspace', 'list', 'position', 'origin_id']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workspace',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='TrelloWorkspace',
        ),
        migrations.AddField(
            model_name='workspacelist',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='workspaces.Workspace'),
        ),
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspaces.WorkspaceList'),
        ),
    ]
