# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_add_workspace_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='sync',
            field=models.BooleanField(default=False),
        ),
    ]
