# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_add_workspace_sync_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'get_latest_by': 'created_at', 'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='projects',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='workspaces', to='projects.Project'),
        ),
    ]
