# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_tune_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='default_list_task_state',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], help_text='The default task state for new lists', max_length=20, null=True),
        ),
    ]
