# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_add_workspace_default_list_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubdatasource',
            name='organization',
            field=models.CharField(default='', max_length=100, verbose_name='GitHub organization ID'),
            preserve_default=False,
        ),
    ]
