# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_add_github_organization_to_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.CharField(db_index=True, max_length=100)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='workspaces.DataSource')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'created_at', 'ordering': ['workspace', 'list', 'position', '-created_at', '-origin_id']},
        ),
        migrations.AlterUniqueTogether(
            name='datasourcewebhook',
            unique_together=set([('data_source', 'origin_id')]),
        ),
    ]
