# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_add_webhook_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'created_at', 'ordering': ['-updated_at', 'workspace', 'list', 'position', '-created_at', '-origin_id']},
        ),
    ]
