# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_task_ordering_and_meta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='url',
            field=models.URLField(help_text='The external URL which allows the user to examine the workspace', null=True),
        ),
    ]
