# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_add_extra_data_to_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workspaces.WorkspaceList'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='workspaces.DataSource'),
        ),
        migrations.AlterField(
            model_name='workspacelist',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
