# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helusers', '0001_add_ad_groups'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_groups',
            field=models.ManyToManyField(blank=True, to='helusers.ADGroup'),
        ),
    ]
