# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_change_user_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
