# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20161024_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.DataSource')),
                ('key', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=50, verbose_name='Trello organization ID')),
            ],
            bases=('projects.datasource',),
        ),
        migrations.CreateModel(
            name='TrelloWorkspace',
            fields=[
                ('workspace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Workspace')),
                ('in_progress_list', models.CharField(max_length=100)),
            ],
            bases=('projects.workspace',),
        ),
        migrations.AddField(
            model_name='workspace',
            name='state',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], db_index=True, default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('github', 'GitHub'), ('trello', 'Trello')], max_length=20),
        ),
    ]
