# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_trello_datasource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='project',
        ),
        migrations.AddField(
            model_name='workspace',
            name='projects',
            field=models.ManyToManyField(db_index=True, related_name='workspaces', to='projects.Project'),
        ),
    ]
