# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_make_workspace_projects_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='datasourceuser',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together=set([('data_source', 'origin_id')]),
        ),
    ]
