# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0004_tune_meta'),
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('user', 'task', 'date')]),
        ),
    ]
